### PR TITLE
Added a workaround to get the WhatsApp data from android when it is not possible to extract it directly using main.py

### PR DESCRIPTION
**Pull request by dtiziano**
See the comments added in readme.md

### CODE REVIEW

**Review by mukulkadel — COMMENTED** [review]
.DS_Store - What's the purpose of this file?

**Comment by dtiziano** [comment]
> .DS_Store - What's the purpose of this file?

It's a folder Information on Mac OS, so not relevant to the commit. Should be deleted.

**Comment by latuminggi** [comment]
hi @dtiziano 
is this PR also resolved issue #7 ?

**Comment by dtiziano** [comment]
> hi @dtiziano 
> 
> is this PR also resolved issue #7 ?

Unfortunately it does not

**Pull request merged**
